### ISSUE TITLE
Create / Add "Visit Repo" Button.

### ISSUE THREAD

**Issue by vivek-30** [nishantwrp/gsoc-organizations#100]
![Screenshot 2023-03-29 at 9 33 00 PM](https://user-images.githubusercontent.com/75980147/228599972-3d2611c1-d554-439d-8048-d709df77e423.jpg)

As you can see in the above ScreenShot There is no "Visit Repo" sort of button available. so it will be great to have it.
Reason: It's seems minor thing to have but trust me it solves major drawback of not having any repo link.
I mean currently we have to search a particular ORG in GitHub search system. so it would be great if we can directly navigate through your website.
Hope it makes sense to you and thanks 😊.

**Comment by beingnoble03** [comment]
This feature was discussed but there's an obstruction: we need to search for github repos manually, also there's no guarantee that the org is available on github itself. For instance, Libre space foundation use gitlab for open source contributions.

**Comment by vivek-30** [comment]
yes you are right, some ORGs uses other code hosting platform, and this is the major issue. Else we can cover 90% of GitHub orgs using a generic route like - `https://github.com/{org_name}`. so overhead of providing new orgs link manually is almost negligible.

**Comment by vivek-30** [comment]
one more thing i wanted to ask is: should i close this issue then ???

**Comment by nishantwrp** [comment]
Closing in favour of #81.
