### ISSUE TITLE
ADD GOOD FOR FIRST-TIMERS TAG

### ISSUE THREAD

**Issue by arimallick** [nishantwrp/gsoc-organizations#102]
Another category in the First-time-organisations (`Shortcuts`) list would be:

**GOOD FOR FIRST-TIMERS** 
(or this can be a separate page highlighting easy-to-start projects from various organisations)

**Comment by nishantwrp** [comment]
On what basis do you think we can highlight easy to start projects?

**Comment by IAmRiteshKoushik** [comment]
I think we can try doing something similar to [Quine](https://quine.sh) where the issues of the GitHub repo are taken and a ranking system is made based on the count of the `Good-First-Issues`. This is just a thought, we could discuss further if we are pursuing this idea ?

**Comment by nishantwrp** [comment]
Not each org has code hosted on GitHub.
