### ISSUE TITLE
Problem with listing and sorting of Years list.

### ISSUE THREAD

**Issue by Girish-Gaurav-Sharma** [nishantwrp/gsoc-organizations#106]
When organizing organizations by years, placing the selected year at the top of the list can create some disorder in the sequence of years. It might be more preferable to mark the selected year without altering its position in the list, which would enhance readability.
![image](https://github.com/nishantwrp/gsoc-organizations/assets/135326401/268dc091-2b3b-41aa-809c-93918bcc75aa)

**Comment by aryansharma6827** [comment]
i would like to solve the issue please assign it to me

**Comment by beingnoble03** [comment]
This was intentionally implemented during development to facilitate user navigation through selected years. So, this issue falls outside our current requirements. Therefore, we are closing it.
