### ISSUE TITLE
Inaccurate projects being recorded

### ISSUE THREAD

**Issue by aryangupta701** [nishantwrp/gsoc-organizations#111]
In AboutCode organization 7 projects got implemented but these two links show different results. I know this is a bug from google side but we can do something from our end to check for the maximum of both the links? I am sure the number will never be more than the real one. 

https://summerofcode.withgoogle.com/archive/2023/organizations/aboutcode
https://summerofcode.withgoogle.com/programs/2023/organizations/aboutcode

**Comment by beingnoble03** [comment]
Hey @aryangupta701, thanks for reaching out. But, the results at `https://summerofcode.withgoogle.com/programs/2023/organizations/aboutcode` are correct. There's a bug in 2023 archive web results, it showed combined results of 2022 and 2023. In 2022, for aboutCode 5 projects were selected and in 2023, 2 projects. So, `https://summerofcode.withgoogle.com/archive/2023/organizations/aboutcode` shows a total of 7 projects, while there were only 2 projects selected in total for year 2023.

So, the results at `gsocorganizations.dev` are completely fine.

**Comment by aryangupta701** [comment]
ohh got it. Thank you.
