### ISSUE TITLE
GitHub link not available.

### ISSUE THREAD

**Issue by SaiDevaHarshaR** [nishantwrp/gsoc-organizations#112]
The absence of a GitHub link for the projects becomes evident upon clicking, and it would be advantageous to include the GitHub link for enhanced accessibility and collaboration.

**Comment by nishantwrp** [comment]
We already discussed why this is infeasible (Refer - #67). But please see https://github.com/nishantwrp/gsoc-organizations/issues/81 on ideas on how this can be fixed.

**Comment by SaiDevaHarshaR** [comment]
Thank you
