### ISSUE TITLE
The add placement is wrong and interferes the content display

### ISSUE THREAD

**Issue by vinutnaruni** [nishantwrp/gsoc-organizations#113]
The current placement of ads on the website is interfering with the content display of the website.
The search bar is not placed in an appropriate position
The content is visible even above and below the search bar while scrolling.

POSSIBLE SOLUTION:
Pushing a search bar a bit up along the x-axis would solve the problem.
or keeping a white strip that hides the extra bar above the search bar would also help.

<img width="1710" alt="Screenshot 2024-01-20 at 10 32 57 PM" src="https://github.com/nishantwrp/gsoc-organizations/assets/142968419/837ae1e7-a6e2-4e3d-a25b-6628388d5bec">

<img width="1710" alt="Screenshot 2024-01-20 at 10 32 44 PM" src="https://github.com/nishantwrp/gsoc-organizations/assets/142968419/dc0cbca7-83e3-4aad-a39d-297b0c7fdc50">

**Comment by nishantwrp** [comment]
Removed these ads. Thanks for the issue!
