### ISSUE TITLE
Add the github link of an org in the org info page 

### ISSUE THREAD

**Issue by thrishank** [nishantwrp/gsoc-organizations#114]
Feature Request:
I would like to propose the addition of a GitHub link to the organization information (ex. https://www.gsocorganizations.dev/organization/submitty/). This would enhance the user experience by providing direct access to the organization's GitHub repository.

**Comment by nishantwrp** [comment]
Please refer https://github.com/nishantwrp/gsoc-organizations/issues/112#issuecomment-1901002667.
