### ISSUE TITLE
fix(view code button): redirect to the correct code repository instead of internship report

### ISSUE THREAD

**Issue by Bittukr7479** [nishantwrp/gsoc-organizations#136]
Description:
Currently, when clicking the "View Code" button on this [projects/SSLDebYv](https://summerofcode.withgoogle.com/programs/2024/projects/SSLDebYv), the link incorrectly redirects to this [Google Docs page](https://docs.google.com/document/d/1LE-HC8CorY9f2Y2q5SOa7ensVUXGZlrf4WWKOtFNHmo/edit?tab=t.0#heading=h.eswae5zens8p), which contains the internship report. This pull request resolves the issue by updating the link to point to the respective code repository, ensuring users are directed to the correct location.

**Comment by mohan-marwari** [comment]
Hi @Bittukr7479 

this issue official [Google Summer of Code](https://summerofcode.withgoogle.com/) website.

**Comment by Bittukr7479** [comment]
> Hi @Bittukr7479
> 
> this issue official [Google Summer of Code](https://summerofcode.withgoogle.com/) website.

Sorry, I apologize for the confusion regarding this issue. Thank you for bringing it to my attention
