### ISSUE TITLE
Minor UI bug in project cards

### ISSUE THREAD

**Issue by nishantwrp** [nishantwrp/gsoc-organizations#73]
<img width="707" alt="Screenshot 2022-05-24 at 12 43 58 AM" src="https://user-images.githubusercontent.com/36989112/169891244-d5a9585a-9aea-40dd-8095-d7197951a525.png">

**Comment by nishantwrp** [comment]
Hi @shadyy41, here's how I reproduced it.

- Go to any organization page from Safari. For example - https://www.gsocorganizations.dev/organization/oppia-foundation/
- Enter responsive design mode in safari 
- Click on IPad (9.7'')
- Scroll down to a project card

**Comment by MahendraBishnoi29** [comment]
@nishantwrp it's not only in iPad it's everywhere.
