### ISSUE TITLE
UI Bug in organisation page in mobile view

### ISSUE THREAD

**Issue by beingnoble03** [nishantwrp/gsoc-organizations#75]
<img width="1440" alt="Screenshot 2022-05-25 at 11 14 47 PM" src="https://user-images.githubusercontent.com/62551163/170329251-d903b2cc-6b39-4056-85ad-164febc0926f.png">

All the years are not visible in the past projects tab.

**Comment by thisisharsh7** [comment]
can I work on this issue??
