### ISSUE TITLE
The data is outdated

### ISSUE THREAD

**Issue by nuromirzak** [nishantwrp/gsoc-organizations#83]
`GET https://api.gsocorganizations.dev/2022.json` returns 197 organizations, while there are 198 organizations on the GSoC website, and it seems that this missing organization is the Eclipse Foundation.

**Comment by nuromirzak** [comment]
It turns out the enumeration starts with 0, not 1. (Yes, I'm a programmer, but I didn't notice it😓). But there are two GeomScale.

**Comment by nishantwrp** [comment]
Closing in favour of #84
