### ISSUE TITLE
GSOC 2023 Organizations announced

### ISSUE THREAD

**Issue by gptsarthak** [nishantwrp/gsoc-organizations#95]
GSOC 2023 Organizations have been announced here https://summerofcode.withgoogle.com/programs/2023/organizations
Can we please update the website to filter out new orgs?

**Comment by jeromtom** [comment]
Hey @gptsarthak the new/first-time orgs have been filtered and mentioned in my blog, Do check it out. Surely, it needs to be added to the website.

**Comment by jeromtom** [comment]
Oops, forget to link the blog: https://jeromtom.hashnode.dev/which-gsoc-organization-to-contribute-to-for-beginners
